=== cafecito-games/Foundry/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:sequence>
										<!-- Present only for a tagged-union case that carries a payload, one entry per field. -->
										<xs:element name="payload_field" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<!-- `xs:int`, not `xs:byte` like a method `<param>`: FoundryScript places no
												     small limit on a tagged-union payload, and `index` mirrors the field's
												     position in a `Vector<TupleFieldDoc>`, whose own size is an `int`. -->
												<xs:attribute type="xs:int" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" />
									<xs:attribute type="xs:string" name="value" />
									<xs:attribute type="xs:string" name="enum" use="optional" />
									<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="enums" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="enum" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<!-- True for a FoundryScript tagged union: an enum whose cases are constructors and values, not integer constants. -->
											<xs:attribute type="xs:boolean" name="is_tagged_union" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="namespace" use="optional" />
			<xs:attribute type="xs:string" name="inherits" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cafecito-games/Foundry/doc/classes/MeshConvexDecompositionSettings.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MeshConvexDecompositionSettings" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Parameters to be used with a [Mesh] convex decomposition operation.
	</brief_description>
	<description>
		Parameters to be used with a [Mesh] convex decomposition operation.
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="convex_hull_approximation" type="bool" setter="set_convex_hull_approximation" getter="get_convex_hull_approximation" default="true">
			If [code]true[/code], uses approximation for computing convex hulls.
		</member>
		<member name="convex_hull_downsampling" type="uint" setter="set_convex_hull_downsampling" getter="get_convex_hull_downsampling" default="4UL">
			Controls the precision of the convex-hull generation process during the clipping plane selection stage. Ranges from [code]1[/code] to [code]16[/code].
		</member>
		<member name="max_concavity" type="float" setter="set_max_concavity" getter="get_max_concavity" default="1.0">
			Maximum concavity. Ranges from [code]0.0[/code] to [code]1.0[/code].
		</member>
		<member name="max_convex_hulls" type="uint" setter="set_max_convex_hulls" getter="get_max_convex_hulls" default="1UL">
			The maximum number of convex hulls to produce from the merge operation.
		</member>
		<member name="max_num_vertices_per_convex_hull" type="uint" setter="set_max_num_vertices_per_convex_hull" getter="get_max_num_vertices_per_convex_hull" default="32UL">
			Controls the maximum number of triangles per convex-hull. Ranges from [code]4[/code] to [code]1024[/code].
		</member>
		<member name="min_volume_per_convex_hull" type="float" setter="set_min_volume_per_convex_hull" getter="get_min_volume_per_convex_hull" default="0.0001">
			Controls the adaptive sampling of the generated convex-hulls. Ranges from [code]0.0[/code] to [code]0.01[/code].
		</member>
		<member name="mode" type="int" setter="set_mode" getter="get_mode" enum="MeshConvexDecompositionSettings.Mode" default="CONVEX_DECOMPOSITION_MODE_VOXEL">
			Mode for the approximate convex decomposition.
		</member>
		<member name="normalize_mesh" type="bool" setter="set_normalize_mesh" getter="get_normalize_mesh" default="false">
			If [code]true[/code], normalizes the mesh before applying the convex decomposition.
		</member>
		<member name="plane_downsampling" type="uint" setter="set_plane_downsampling" getter="get_plane_downsampling" default="4UL">
			Controls the granularity of the search for the "best" clipping plane. Ranges from [code]1[/code] to [code]16[/code].
		</member>
		<member name="project_hull_vertices" type="bool" setter="set_project_hull_vertices" getter="get_project_hull_vertices" default="true">
			If [code]true[/code], projects output convex hull vertices onto the original source mesh to increase floating-point accuracy of the results.
		</member>
		<member name="resolution" type="uint" setter="set_resolution" getter="get_resolution" default="10000UL">
			Maximum number of voxels generated during the voxelization stage.
		</member>
		<member name="revolution_axes_clipping_bias" type="float" setter="set_revolution_axes_clipping_bias" getter="get_revolution_axes_clipping_bias" default="0.05">
			Controls the bias toward clipping along revolution axes. Ranges from [code]0.0[/code] to [code]1.0[/code].
		</member>
		<member name="symmetry_planes_clipping_bias" type="float" setter="set_symmetry_planes_clipping_bias" getter="get_symmetry_planes_clipping_bias" default="0.05">
			Controls the bias toward clipping along symmetry planes. Ranges from [code]0.0[/code] to [code]1.0[/code].
		</member>
	</members>
	<constants>
		<constant name="CONVEX_DECOMPOSITION_MODE_VOXEL" value="0" enum="Mode">
			Constant for voxel-based approximate convex decomposition.
		</constant>
		<constant name="CONVEX_DECOMPOSITION_MODE_TETRAHEDRON" value="1" enum="Mode">
			Constant for tetrahedron-based approximate convex decomposition.
		</constant>
	</constants>
</class>

=== cafecito-games/Foundry/modules/gltf/doc_classes/GLTFLight.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="GLTFLight" inherits="Resource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		Represents a glTF light.
	</brief_description>
	<description>
		Represents a light as defined by the [code]KHR_lights_punctual[/code] glTF extension.
	</description>
	<tutorials>
		<link title="Runtime file loading and saving">$DOCS_URL/tutorials/io/runtime_file_loading_and_saving.html</link>
		<link title="KHR_lights_punctual glTF extension spec">https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual</link>
	</tutorials>
	<methods>
		<method name="from_dictionary" qualifiers="static">
			<return type="GLTFLight" />
			<param index="0" name="dictionary" type="Dictionary" />
			<description>
				Creates a new GLTFLight instance by parsing the given [Dictionary].
			</description>
		</method>
		<method name="from_node" qualifiers="static">
			<return type="GLTFLight" />
			<param index="0" name="light_node" type="Light3D" />
			<description>
				Create a new GLTFLight instance from the given Foundry [Light3D] node.
			</description>
		</method>
		<method name="get_additional_data">
			<return type="Variant" />
			<param index="0" name="extension_name" type="StringName" />
			<description>
			</description>
		</method>
		<method name="set_additional_data">
			<return type="void" />
			<param index="0" name="extension_name" type="StringName" />
			<param index="1" name="additional_data" type="Variant" />
			<description>
			</description>
		</method>
		<method name="to_dictionary" qualifiers="const">
			<return type="Dictionary" />
			<description>
				Serializes this GLTFLight instance into a [Dictionary].
			</description>
		</method>
		<method name="to_node" qualifiers="const">
			<return type="Light3D" />
			<description>
				Converts this GLTFLight instance into a Foundry [Light3D] node.
			</description>
		</method>
	</methods>
	<members>
		<member name="color" type="Color" setter="set_color" getter="get_color" default="Color(1, 1, 1, 1)" keywords="colour">
			The [Color] of the light in linear space. Defaults to white. A black color causes the light to have no effect.
			This value is linear to match glTF, but will be converted to nonlinear sRGB when creating a Foundry [Light3D] node upon import, or converted to linear when exporting a Foundry [Light3D] to glTF.
		</member>
		<member name="inner_cone_angle" type="float" setter="set_inner_cone_angle" getter="get_inner_cone_angle" default="0.0">
			The inner angle of the cone in a spotlight. Must be less than or equal to the outer cone angle.
			Within this angle, the light is at full brightness. Between the inner and outer cone angles, there is a transition from full brightness to zero brightness. When creating a Foundry [SpotLight3D], the ratio between the inner and outer cone angles is used to calculate the attenuation of the light.
		</member>
		<member name="intensity" type="float" setter="set_intensity" getter="get_intensity" default="1.0">
			The intensity of the light. This is expressed in candelas (lumens per steradian) for point and spot lights, and lux (lumens per m²) for directional lights. When creating a Foundry light, this value is converted to a unitless multiplier.
		</member>
		<member name="light_type" type="String" setter="set_light_type" getter="get_light_type" default="&quot;&quot;">
			The type of the light. The values accepted by Foundry are "point", "spot", and "directional", which correspond to Foundry's [OmniLight3D], [SpotLight3D], and [DirectionalLight3D] respectively.
		</member>
		<member name="outer_cone_angle" type="float" setter="set_outer_cone_angle" getter="get_outer_cone_angle" default="0.7853982">
			The outer angle of the cone in a spotlight. Must be greater than or equal to the inner angle.
			At this angle, the light drops off to zero brightness. Between the inner and outer cone angles, there is a transition from full brightness to zero brightness. If this angle is a half turn, then the spotlight emits in all directions. When creating a Foundry [SpotLight3D], the outer cone angle is used as the angle of the spotlight.
		</member>
		<member name="range" type="float" setter="set_range" getter="get_range" default="inf">
			The range of the light, beyond which the light has no effect. glTF lights with no range defined behave like physical lights (which have infinite range). When creating a Foundry light, the range is clamped to [code]4096.0[/code].
		</member>
	</members>
</class>
