=== cafecito-games/Foundry/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:sequence>
										<!-- Present only for a tagged-union case that carries a payload, one entry per field. -->
										<xs:element name="payload_field" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<!-- `xs:int`, not `xs:byte` like a method `<param>`: FoundryScript places no
												     small limit on a tagged-union payload, and `index` mirrors the field's
												     position in a `Vector<TupleFieldDoc>`, whose own size is an `int`. -->
												<xs:attribute type="xs:int" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" />
									<xs:attribute type="xs:string" name="value" />
									<xs:attribute type="xs:string" name="enum" use="optional" />
									<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="enums" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="enum" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<!-- True for a FoundryScript tagged union: an enum whose cases are constructors and values, not integer constants. -->
											<xs:attribute type="xs:boolean" name="is_tagged_union" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="namespace" use="optional" />
			<xs:attribute type="xs:string" name="inherits" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cafecito-games/Foundry/doc/classes/MultiplayerAPIExtension.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MultiplayerAPIExtension" inherits="MultiplayerAPI" keywords="network" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Base class used for extending the [MultiplayerAPI].
	</brief_description>
	<description>
		This class can be used to extend or replace the default [MultiplayerAPI] implementation via script or extensions.
		The following example extend the default implementation ([SceneMultiplayer]) by logging every RPC being made, and every object being configured for replication.
		[codeblocks]
		[foundry_script]
		extends MultiplayerAPIExtension
		class_name LogMultiplayer

		# We want to extend the default SceneMultiplayer.
		var base_multiplayer = SceneMultiplayer.new()

		func _init():
			# Just passthrough base signals (copied to var to avoid cyclic reference)
			var cts = connected_to_server
			var cf = connection_failed
			var sd = server_disconnected
			var pc = peer_connected
			var pd = peer_disconnected
			base_multiplayer.connected_to_server.connect(func(): cts.emit())
			base_multiplayer.connection_failed.connect(func(): cf.emit())
			base_multiplayer.server_disconnected.connect(func(): sd.emit())
			base_multiplayer.peer_connected.connect(func(id): pc.emit(id))
			base_multiplayer.peer_disconnected.connect(func(id): pd.emit(id))

		func _poll():
			return base_multiplayer.poll()

		# Log RPC being made and forward it to the default multiplayer.
		func _rpc(peer: int, object: Object, method: StringName, args: Array) -&gt; Error:
			print("Got RPC for %d: %s::%s(%s)" % [peer, object, method, args])
			return base_multiplayer.rpc(peer, object, method, args)

		# Log configuration add. E.g. root path (nullptr, NodePath), replication (Node, Spawner|Synchronizer), custom.
		func _object_configuration_add(object, config: Variant) -&gt; Error:
			if config is MultiplayerSynchronizer:
				print("Adding synchronization configuration for %s. Synchronizer: %s" % [object, config])
			elif config is MultiplayerSpawner:
				print("Adding node %s to the spawn list. Spawner: %s" % [object, config])
			return base_multiplayer.object_configuration_add(object, config)

		# Log configuration remove. E.g. root path (nullptr, NodePath), replication (Node, Spawner|Synchronizer), custom.
		func _object_configuration_remove(object, config: Variant) -&gt; Error:
			if config is MultiplayerSynchronizer:
				print("Removing synchronization configuration for %s. Synchronizer: %s" % [object, config])
			elif config is MultiplayerSpawner:
				print("Removing node %s from the spawn list. Spawner: %s" % [object, config])
			return base_multiplayer.object_configuration_remove(object, config)

		# These can be optional, but in our case we want to extend SceneMultiplayer, so forward everything.
		func _set_multiplayer_peer(p_peer: MultiplayerPeer):
			base_multiplayer.multiplayer_peer = p_peer

		func _get_multiplayer_peer() -&gt; MultiplayerPeer:
			return base_multiplayer.multiplayer_peer

		func _get_unique_id() -&gt; int:
			return base_multiplayer.get_unique_id()

		func _get_remote_sender_id() -&gt; int:
			return base_multiplayer.get_remote_sender_id()

		func _get_peer_ids() -&gt; PackedInt32Array:
			return base_multiplayer.get_peers()
		[/foundry_script]
		[/codeblocks]
		Then in your main scene or in an autoload call [method SceneTree.set_multiplayer] to start using your custom [MultiplayerAPI]:
		[codeblocks]
		[foundry_script]
		# autoload.fs
		func _enter_tree():
			# Sets our custom multiplayer as the main one in SceneTree.
			get_tree().set_multiplayer(LogMultiplayer.new())
		[/foundry_script]
		[/codeblocks]
		Native extensions can alternatively use the [method MultiplayerAPI.set_default_interface] method during initialization to configure themselves as the default implementation.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="_get_multiplayer_peer" qualifiers="virtual">
			<return type="MultiplayerPeer" />
			<description>
				Called when the [member MultiplayerAPI.multiplayer_peer] is retrieved.
			</description>
		</method>
		<method name="_get_peer_ids" qualifiers="virtual const">
			<return type="PackedInt32Array" />
			<description>
				Callback for [method MultiplayerAPI.get_peers].
			</description>
		</method>
		<method name="_get_remote_sender_id" qualifiers="virtual const">
			<return type="int" />
			<description>
				Callback for [method MultiplayerAPI.get_remote_sender_id].
			</description>
		</method>
		<method name="_get_unique_id" qualifiers="virtual const">
			<return type="int" />
			<description>
				Callback for [method MultiplayerAPI.get_unique_id].
			</description>
		</method>
		<method name="_object_configuration_add" qualifiers="virtual">
			<return type="int" enum="Error" />
			<param index="0" name="object" type="Object" />
			<param index="1" name="configuration" type="Variant" />
			<description>
				Callback for [method MultiplayerAPI.object_configuration_add].
			</description>
		</method>
		<method name="_object_configuration_remove" qualifiers="virtual">
			<return type="int" enum="Error" />
			<param index="0" name="object" type="Object" />
			<param index="1" name="configuration" type="Variant" />
			<description>
				Callback for [method MultiplayerAPI.object_configuration_remove].
			</description>
		</method>
		<method name="_poll" qualifiers="virtual">
			<return type="int" enum="Error" />
			<description>
				Callback for [method MultiplayerAPI.poll].
			</description>
		</method>
		<method name="_rpc" qualifiers="virtual">
			<return type="int" enum="Error" />
			<param index="0" name="peer" type="int" />
			<param index="1" name="object" type="Object" />
			<param index="2" name="method" type="StringName" />
			<param index="3" name="args" type="Array" />
			<description>
				Callback for [method MultiplayerAPI.rpc].
			</description>
		</method>
		<method name="_set_multiplayer_peer" qualifiers="virtual">
			<return type="void" />
			<param index="0" name="multiplayer_peer" type="MultiplayerPeer" />
			<description>
				Called when the [member MultiplayerAPI.multiplayer_peer] is set.
			</description>
		</method>
	</methods>
</class>

=== cafecito-games/Foundry/doc/classes/GPUParticlesCollisionSDF3D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="GPUParticlesCollisionSDF3D" inherits="GPUParticlesCollision3D" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		A baked signed distance field 3D particle collision shape affecting [GPUParticles3D] nodes.
	</brief_description>
	<description>
		A baked signed distance field 3D particle collision shape affecting [GPUParticles3D] nodes.
		Signed distance fields (SDF) allow for efficiently representing approximate collision shapes for convex and concave objects of any shape. This is more flexible than [GPUParticlesCollisionHeightField3D], but it requires a baking step.
		[b]Baking:[/b] The signed distance field texture can be baked by selecting the [GPUParticlesCollisionSDF3D] node in the editor, then clicking [b]Bake SDF[/b] at the top of the 3D viewport. Any [i]visible[/i] [MeshInstance3D]s within the [member size] will be taken into account for baking, regardless of their [member GeometryInstance3D.gi_mode].
		[b]Note:[/b] Baking a [GPUParticlesCollisionSDF3D]'s [member texture] is only possible within the editor, as there is no bake method exposed for use in exported projects. However, it's still possible to load pre-baked [Texture3D]s into its [member texture] property in an exported project.
		[b]Note:[/b] [member ParticleProcessMaterial.collision_mode] must be [constant ParticleProcessMaterial.COLLISION_RIGID] or [constant ParticleProcessMaterial.COLLISION_HIDE_ON_CONTACT] on the [GPUParticles3D]'s process material for collision to work.
		[b]Note:[/b] Particle collision only affects [GPUParticles3D], not [CPUParticles3D].
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_bake_mask_value" qualifiers="const">
			<return type="bool" />
			<param index="0" name="layer_number" type="int" />
			<description>
				Returns whether or not the specified layer of the [member bake_mask] is enabled, given a [param layer_number] between 1 and 32.
			</description>
		</method>
		<method name="set_bake_mask_value">
			<return type="void" />
			<param index="0" name="layer_number" type="int" />
			<param index="1" name="value" type="bool" />
			<description>
				Based on [param value], enables or disables the specified layer in the [member bake_mask], given a [param layer_number] between 1 and 32.
			</description>
		</method>
	</methods>
	<members>
		<member name="bake_mask" type="uint" setter="set_bake_mask" getter="get_bake_mask" default="4294967295UL">
			The visual layers to account for when baking the particle collision SDF. Only [MeshInstance3D]s whose [member VisualInstance3D.layers] match with this [member bake_mask] will be included in the generated particle collision SDF. By default, all objects are taken into account for the particle collision SDF baking.
		</member>
		<member name="resolution" type="int" setter="set_resolution" getter="get_resolution" enum="GPUParticlesCollisionSDF3D.Resolution" default="RESOLUTION_64">
			The bake resolution to use for the signed distance field [member texture]. The texture must be baked again for changes to the [member resolution] property to be effective. Higher resolutions have a greater performance cost and take more time to bake. Higher resolutions also result in larger baked textures, leading to increased VRAM and storage space requirements. To improve performance and reduce bake times, use the lowest resolution possible for the object you're representing the collision of.
		</member>
		<member name="size" type="Vector3" setter="set_size" getter="get_size" default="Vector3(2, 2, 2)">
			The collision SDF's size in 3D units. To improve SDF quality, the [member size] should be set as small as possible while covering the parts of the scene you need.
		</member>
		<member name="texture" type="Texture3D" setter="set_texture" getter="get_texture">
			The 3D texture representing the signed distance field.
		</member>
		<member name="thickness" type="float" setter="set_thickness" getter="get_thickness" default="1.0">
			The collision shape's thickness. Unlike other particle colliders, [GPUParticlesCollisionSDF3D] is actually hollow on the inside. [member thickness] can be increased to prevent particles from tunneling through the collision shape at high speeds, or when the [GPUParticlesCollisionSDF3D] is moved.
		</member>
	</members>
	<constants>
		<constant name="RESOLUTION_16" value="0" enum="Resolution">
			Bake a 16×16×16 signed distance field. This is the fastest option, but also the least precise.
		</constant>
		<constant name="RESOLUTION_32" value="1" enum="Resolution">
			Bake a 32×32×32 signed distance field.
		</constant>
		<constant name="RESOLUTION_64" value="2" enum="Resolution">
			Bake a 64×64×64 signed distance field.
		</constant>
		<constant name="RESOLUTION_128" value="3" enum="Resolution">
			Bake a 128×128×128 signed distance field.
		</constant>
		<constant name="RESOLUTION_256" value="4" enum="Resolution">
			Bake a 256×256×256 signed distance field.
		</constant>
		<constant name="RESOLUTION_512" value="5" enum="Resolution">
			Bake a 512×512×512 signed distance field. This is the slowest option, but also the most precise.
		</constant>
		<constant name="RESOLUTION_MAX" value="6" enum="Resolution">
			Represents the size of the [enum Resolution] enum.
		</constant>
	</constants>
</class>
